routes/web.php
<?php


use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('decisions/afficher_taux', 'DecisionController@taux')->name('decisions.afficher_taux');

Route::post('decision/tauxremboursement', 'DecisionController@tauxremboursement')->name('decision.tauxremboursement');

Route::resource('categories', 'CategorieController');

Route::resource('professions', 'ProfessionController');

Route::resource('produitcredits', 'ProduitcreditController');

Route::resource('typedemandeurs', 'TypedemandeurController');

Route::resource('sexes', 'SexeController');

Route::resource('sitmatrimoniales', 'SitmatrimonialeController');

Route::resource('niveaux', 'NiveauController');

Route::resource('decisions', 'DecisionController');

app/Models/Decision.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Decision extends Model
{
    //
    protected $table = 'decisions';

    protected $fillable = [
        'refdecision',
        'categorie_id',
        'typedemandeur_id',
        'niveau_id',
        'sexe_id',
        'produitcredit_id',
        'matrimoniale_id',
        'taux',
        'created_at',
        'updated_at'
    ];

    public function categorie()
    {
        return $this->belongsTo(Categorie::class, 'categorie_id');
    }

    public function Typedemandeur()
    {
        return $this->belongsTo(Typedemandeur::class, 'typedemandeur_id');
    }

    public function niveau()
    {
        return $this->belongsTo(Niveau::class, 'niveau_id');
    }

    public function sexe()
    {
        return $this->belongsTo(Sexe::class, 'sexe_id');
    }

    public function produitcredit()
    {
        return $this->belongsTo(Produitcredit::class, 'produitcredit_id');
    }

    public function situationmatrimoniale()
    {
        return $this->belongsTo(Matrimoniale::class, 'matrimoniale_id');
    }
}

app/Http/Controllers/DecisionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\decisionRequestCreate;
use App\Models\Decision;
use App\Models\Categorie;
use App\Models\Matrimoniale;
use App\Models\Niveau;
use App\Models\Produitcredit;
use App\Models\Sexe;
use App\Models\Typedemandeur;
use Illuminate\Http\Request;

class DecisionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $decisions = Decision::all();
        #dd($decisions);
        return view('decisions.index', compact('decisions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $matrimoniales = Matrimoniale::all();
        $produitcredits = Produitcredit::all();
        $sexes = Sexe::all();
        $niveaux = Niveau::all();
        $typedemandeurs = Typedemandeur::all();
        $categories = Categorie::all();
        return view('decisions.create')->with('categories', $categories)->with('typedemandeurs', $typedemandeurs)->with('niveaux', $niveaux)->with('sexes', $sexes)->with('produitcredits', $produitcredits)->with('matrimoniales', $matrimoniales);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(decisionRequestCreate $request)
    {
        //
        $inputs = $request->all();
        $inputs['created_at'] = date('Y-m-d H:i:s');

        Decision::create($inputs);

        return redirect('/decisions')->with('success', 'Décision ajoutée avec succès');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Decision  $decision
     * @return \Illuminate\Http\Response
     */
    public function show(Decision $decision)
    {
        //
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Decision  $decision
     * @return \Illuminate\Http\Response
     */
    public function edit(Decision $decision)
    {
        //
        $matrimoniales = Matrimoniale::all();
        $produitcredits = Produitcredit::all();
        $sexes = Sexe::all();
        $niveaux = Niveau::all();
        $typedemandeurs = Typedemandeur::all();
        $categories = Categorie::all();
        return view('decisions.update', compact('decision', 'categories', 'typedemandeurs', 'niveaux', 'sexes', 'produitcredits', 'matrimoniales'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Decision  $decision
     * @return \Illuminate\Http\Response
     */
    public function update(decisionRequestCreate $request, Decision $decision)
    {
        //
        $inputs = $request->all();
        $inputs['updated_at'] = date('Y-m-d H:i:s');

        $decision->update($inputs);
        return redirect('/decisions')->with('success', 'Décision mis à jour avec succès');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Decision  $decision
     * @return \Illuminate\Http\Response
     */
    public function destroy(Decision $decision)
    {
        //
        $decision->delete();
        $decisions = Decision::all();


        return redirect('/decisions')->with('success', 'Décision supprimée avec succès');
    }

    public function taux(Decision $decision)
    {
        //
        $matrimoniales = Matrimoniale::all();
        $produitcredits = Produitcredit::all();
        $sexes = Sexe::all();
        $niveaux = Niveau::all();
        $typedemandeurs = Typedemandeur::all();
        $categories = Categorie::all();
        return view('decisions.afficher_taux', compact('decision', 'categories', 'typedemandeurs', 'niveaux', 'sexes', 'produitcredits', 'matrimoniales'));
      

    } 

    public function tauxremboursement(Decision $decision)

    {
        //
       Decision::where('id', $decision->id)->select('taux')->get();

    }






}

resources/views/decisions/afficher_taux.blade.php
 @extends('layouts.main')

@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css') }}">
@endsection

@section('content')
    <div class="card">
        <div class="card-header">

        </div>


        <div class="card-body">
            <form method="POST" action="{{ route('decision.tauxremboursement') }}" enctype="multipart/form-data">
                @csrf
                <div class="row">

                        <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="categorie_id">Secteur d'activités</label>
                            <select class="form-control {{ $errors->has('categorie_id') ? 'is-invalid' : '' }}"
                                name="categorie_id" id="categorie_id" required>

                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->libcat }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="typedemandeur_id">Type demandeur</label>
                            <select class="form-control {{ $errors->has('typedemandeur_id') ? 'is-invalid' : '' }}"
                                name="typedemandeur_id" id="typedemandeur_id" required>

                                @foreach ($typedemandeurs as $typedemandeur)
                                    <option value="{{ $typedemandeur->id }}">{{ $typedemandeur->libtype }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="niveau_id">Niveau</label>
                            <select class="form-control {{ $errors->has('niveau_id') ? 'is-invalid' : '' }}"
                                name="niveau_id" id="niveau_id" required>

                                @foreach ($niveaux as $niveau)
                                    <option value="{{ $niveau->id }}">{{ $niveau->libniv }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="sexe_id">Sexe</label>
                            <select class="form-control {{ $errors->has('sexe_id') ? 'is-invalid' : '' }}" name="sexe_id"
                                id="sexe_id" required>

                                @foreach ($sexes as $sex)
                                    <option value="{{ $sex->id }}">{{ $sex->libsexe }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="produitcredit_id">Produit</label>
                            <select class="form-control {{ $errors->has('produitcredit_id') ? 'is-invalid' : '' }}"
                                name="produitcredit_id" id="produitcredit_id" required>

                                @foreach ($produitcredits as $produitcredit)
                                    <option value="{{ $produitcredit->id }}">{{ $produitcredit->libpc }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="matrimoniale_id">Situation matrimoniale</label>
                            <select class="form-control {{ $errors->has('matrimoniale_id') ? 'is-invalid' : '' }}"
                                name="matrimoniale_id" id="matrimoniale_id" required>

                                @foreach ($matrimoniales as $sitmatrimoniale)
                                    <option value="{{ $sitmatrimoniale->id }}">{{ $sitmatrimoniale->libmatri }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>


                    <div class="form-group">
                        <button class="btn btn-danger" type="submit">
                            AFFICHER TAUX DE REMBOURSEMENT
                        </button>
                    </div>
            </form>
        </div>
    </div>
@endsection
@section('js')
    <script src="{{ asset('adminlte/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
    <script>
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    </script>
@endsection

resources/views/decisions/create.blade.php
@extends('layouts.main')

@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css') }}">
@endsection

@section('content')
    <div class="card">
        <div class="card-header">

        </div>


        <div class="card-body">
            <form method="POST" action="{{ route('decisions.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="row">

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="refdecision">Référence décision</label>
                            <input class="form-control {{ $errors->has('refdecision') ? 'is-invalid' : '' }}"
                                type="text" name="refdecision" id="refdecision" value="{{ old('refdecision', '') }}"
                                required>

                            @if ($errors->has('refdecision'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('refdecision') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="categorie_id">Libellé de la catégorie</label>
                            <select class="form-control {{ $errors->has('categorie_id') ? 'is-invalid' : '' }}"
                                name="categorie_id" id="categorie_id" required>

                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->libcat }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="typedemandeur_id">Type demandeur</label>
                            <select class="form-control {{ $errors->has('typedemandeur_id') ? 'is-invalid' : '' }}"
                                name="typedemandeur_id" id="typedemandeur_id" required>

                                @foreach ($typedemandeurs as $typedemandeur)
                                    <option value="{{ $typedemandeur->id }}">{{ $typedemandeur->libtype }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="niveau_id">Niveau</label>
                            <select class="form-control {{ $errors->has('niveau_id') ? 'is-invalid' : '' }}"
                                name="niveau_id" id="niveau_id" required>

                                @foreach ($niveaux as $niveau)
                                    <option value="{{ $niveau->id }}">{{ $niveau->libniv }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="sexe_id">Sexe</label>
                            <select class="form-control {{ $errors->has('sexe_id') ? 'is-invalid' : '' }}" name="sexe_id"
                                id="sexe_id" required>

                                @foreach ($sexes as $sex)
                                    <option value="{{ $sex->id }}">{{ $sex->libsexe }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="produitcredit_id">Produit</label>
                            <select class="form-control {{ $errors->has('produitcredit_id') ? 'is-invalid' : '' }}"
                                name="produitcredit_id" id="produitcredit_id" required>

                                @foreach ($produitcredits as $produitcredit)
                                    <option value="{{ $produitcredit->id }}">{{ $produitcredit->libpc }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="matrimoniale_id">Situation matrimoniale</label>
                            <select class="form-control {{ $errors->has('matrimoniale_id') ? 'is-invalid' : '' }}"
                                name="matrimoniale_id" id="matrimoniale_id" required>

                                @foreach ($matrimoniales as $sitmatrimoniale)
                                    <option value="{{ $sitmatrimoniale->id }}">{{ $sitmatrimoniale->libmatri }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="taux">Taux de remboursement</label>
                            <input class="form-control {{ $errors->has('taux') ? 'is-invalid' : '' }}" type="text"
                                name="taux" id="taux" value="{{ old('taux', '') }}" required>

                            @if ($errors->has('taux'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('taux') }}
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-danger" type="submit">
                            Validez
                        </button>
                    </div>
            </form>
        </div>
    </div>
@endsection
@section('js')
    <script src="{{ asset('adminlte/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
    <script>
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    </script>
@endsection

resources/views/decisions/index.blade.php
@extends('layouts.main')
@section('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">
@endsection
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="col-sm-2 pull-right" style="margin-bottom: 10px">

                    <a href="{{ route('home') }}">
                        <button type="button" class="btn btn-block btn-outline-primary btn-sm">Retour</button>
                    </a>

                </div>

                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Liste des décisions</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped datatable-Transaction">
                            <thead>
                                <tr>

                                    <th>Référence décision</th>
                                    <th>Secteur d'activités</th>
                                    <th>Type demandeur</th>
                                    <th>Niveau</th>
                                    <th>Sexe</th>
                                    <th>Produit</th>
                                    <th>Situation matrimoniale</th>
                                    <th>Taux de remboursement</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($decisions as $key => $decision)
                                    <tr>


                                        <td>{{ $decision->refdecision ?? '' }}</td>
                                        <td>{{ $decision->categorie->libcat ?? '' }}</td>
                                        <td>{{ $decision->typedemandeur->libtype ?? '' }}</td>
                                        <td>{{ $decision->niveau->libniv ?? '' }}</td>
                                        <td>{{ $decision->sexe->libsexe ?? '' }}</td>
                                        <td>{{ $decision->produitcredit->libpc ?? '' }}</td>
                                        <td>{{ $decision->situationmatrimoniale->libmatri ?? '' }}</td>
                                        <td>{{ $decision->taux ?? '' }}</td>




                                        <td class="">
                                            <div class="btn-group btn-group-sm">
                                                {!! Form::open(['route' => ['decisions.destroy', $decision->id], 'method' => 'delete']) !!}
                                                <div class='btn-group'>

                                                    <a href="{{ route('decisions.edit', $decision->id) }}"
                                                        class='btn btn-warning'>
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                    {!! Form::button('<i class="fa fa-trash"></i>', [
                                                        'type' => 'submit',
                                                        'class' => 'btn btn-sm  btn-square btn-danger',
                                                        'onclick' => "return confirm('Êtes vous sûr de supprimer ?')",
                                                    ]) !!}

                                                </div>
                                                {!! Form::close() !!}



                                            </div>
                                        </td>



                                    </tr>
                                @endforeach



                            </tbody>
                            <tfoot>
                                <tr>


                                    <th>Référence décision</th>
                                    <th>Secteur d'activités</th>
                                    <th>Type demandeur</th>
                                    <th>Niveau</th>
                                    <th>Sexe</th>
                                    <th>Produit</th>
                                    <th>Situation matrimoniale</th>
                                    <th>Taux de remboursement</th>

                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->


    </section>
@endsection
@section('js')
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>

    <script>
        $(function() {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
                dom: 'Bfrtip',
                buttons: [

                    'excelHtml5',
                    'csvHtml5',
                    'pdfHtml5'
                ]
            });





        });
    </script>
@endsection