routes/web.php
<?php


use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('decisions/afficher_taux', 'DecisionController@taux')->name('decisions.afficher_taux');

Route::post('decision/tauxremboursement', 'DecisionController@tauxremboursement')->name('decision.tauxremboursement');

Route::resource('categories', 'CategorieController');

Route::resource('professions', 'ProfessionController');

Route::resource('produitcredits', 'ProduitcreditController');

Route::resource('typedemandeurs', 'TypedemandeurController');

Route::resource('sexes', 'SexeController');

Route::resource('sitmatrimoniales', 'SitmatrimonialeController');

Route::resource('niveaux', 'NiveauController');

Route::resource('decisions', 'DecisionController');

app/Models/Profession.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Profession extends Model
{
    //

    protected $table = 'professions';

    protected $fillable = [
        'codeprofession',
        'libprofession',
        'categorie_id',
        'created_at',
        'updated_at'
    ];

    public function categorie()
    {
        return $this->belongsTo(Categorie::class);
    }
}

app/Http/Controllers/ProfessionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categorie;
use App\Models\Profession;
use Illuminate\Http\Request;

use App\http\Requests\professionRequestCreate;

class ProfessionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $professions = Profession::all();
        return view('professions.index', compact('professions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Categorie::all();
        return view('professions.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(professionRequestCreate  $request)
    {
        //
        $inputs = $request->all();
        $inputs['created_at'] = date('Y-m-d H:i:s');

        Profession::create($inputs);

        return redirect('/professions')->with('success', 'Profession ajoutée avec succès');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Profession  $profession
     * @return \Illuminate\Http\Response
     */
    public function show(Profession $profession)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Profession  $profession
     * @return \Illuminate\Http\Response
     */
    public function edit(Profession $profession)
    {
        //
        $categories = Categorie::all();
        return view('professions.update', compact('profession', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Profession  $profession
     * @return \Illuminate\Http\Response
     */
    public function update(professionRequestCreate $request, Profession $profession)
    {
        //
        $inputs = $request->all();
        $inputs['updated_at'] = date('Y-m-d H:i:s');

        $profession->update($inputs);
        return redirect('/professions')->with('success', 'Profession mis à jour avec succès');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Profession  $profession
     * @return \Illuminate\Http\Response
     */
    public function destroy(Profession $profession)
    {
        //
        $profession->delete();
        $professions = Profession::all();


        return redirect('/professions')->with('success', 'Profession supprimée avec succès');
    }
}

resources/views/professions/create.blade.php
@extends('layouts.main')

@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css') }}">
@endsection

@section('content')
    <div class="card">
        <div class="card-header">

        </div>


        <div class="card-body">
            <form method="POST" action="{{ route('professions.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="row">

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="codeprofession">Code de la profession</label>
                            <input class="form-control {{ $errors->has('codeprofession') ? 'is-invalid' : '' }}"
                                type="text" name="codeprofession" id="codeprofession"
                                value="{{ old('codeprofession', '') }}" required>

                            @if ($errors->has('codeprofession'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('codeprofession') }}
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="libprofession">Libellé de la profession</label>
                            <input class="form-control {{ $errors->has('libprofession') ? 'is-invalid' : '' }}"
                                type="text" name="libprofession" id="libprofession"
                                value="{{ old('libprofession', '') }}" required>

                            @if ($errors->has('libprofession'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('libprofession') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="categorie_id">Libellé de la catégorie</label>
                            <select class="form-control {{ $errors->has('categorie_id') ? 'is-invalid' : '' }}"
                                name="categorie_id" id="categorie_id" required>

                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->libcat }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-danger" type="submit">
                            Validez
                        </button>
                    </div>
            </form>
        </div>
    </div>
@endsection
@section('js')
    <script src="{{ asset('adminlte/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
    <script>
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    </script>
@endsection

resources/views/professions/index.blade.php
@extends('layouts.main')
@section('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">
@endsection
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="col-sm-2 pull-right" style="margin-bottom: 10px">

                    <a href="{{ route('home') }}">
                        <button type="button" class="btn btn-block btn-outline-primary btn-sm">Retour</button>
                    </a>

                </div>

                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Liste des professions</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped datatable-Transaction">
                            <thead>
                                <tr>

                                    <th>Code de la profession</th>
                                    <th>Libellé de la profession</th>
                                    <th>Libellé de la catégorie</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($professions as $key => $profession)
                                    <tr>


                                        <td>{{ $profession->codeprofession ?? '' }}</td>
                                        <td>{{ $profession->libprofession ?? '' }}</td>
                                        <td>{{ $profession->categorie->libcat ?? '' }}</td>




                                        <td class="">
                                            <div class="btn-group btn-group-sm">
                                                {!! Form::open(['route' => ['professions.destroy', $profession->id], 'method' => 'delete']) !!}
                                                <div class='btn-group'>

                                                    <a href="{{ route('professions.edit', $profession->id) }}"
                                                        class='btn btn-warning'>
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                    {!! Form::button('<i class="fa fa-trash"></i>', [
                                                        'type' => 'submit',
                                                        'class' => 'btn btn-sm  btn-square btn-danger',
                                                        'onclick' => "return confirm('Êtes vous sûr de supprimer ?')",
                                                    ]) !!}

                                                </div>
                                                {!! Form::close() !!}



                                            </div>
                                        </td>



                                    </tr>
                                @endforeach



                            </tbody>
                            <tfoot>
                                <tr>


                                    <th>Code de la profession</th>
                                    <th>Libellé de la profession</th>
                                    <th>Libellé de la catégorie</th>

                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->


    </section>
@endsection
@section('js')
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>

    <script>
        $(function() {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
                dom: 'Bfrtip',
                buttons: [

                    'excelHtml5',
                    'csvHtml5',
                    'pdfHtml5'
                ]
            });





        });
    </script>
@endsection

resources/views/professions/update.blade.php
@extends('layouts.main')

@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css') }}">
@endsection

@section('content')
    <div class="card">
        <div class="card-header">

        </div>

        <div class="card-body">
            <form method="POST" action="{{ route('professions.update', [$profession->id]) }}"
                enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="row">

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="codeprofession">Libelé de la profession</label>
                            <input class="form-control {{ $errors->has('codeprofession') ? 'is-invalid' : '' }}"
                                type="text" name="codeprofession" id="codeprofession"
                                value="{{ $profession->codeprofession }}" required>

                            @if ($errors->has('codeprofession'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('codeprofession') }}
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="libprofession">Libelé de la profession</label>
                            <input class="form-control {{ $errors->has('libprofession') ? 'is-invalid' : '' }}"
                                type="text" name="libprofession" id="libprofession"
                                value="{{ $profession->libprofession }}" required>

                            @if ($errors->has('libprofession'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('libprofession') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="categorie_id">Libelé de la catégorie</label>
                            <select class="form-control {{ $errors->has('categorie_id') ? 'is-invalid' : '' }}"
                                name="categorie_id" id="categorie_id">

                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}"
                                        @if (old('categorie_id', $category->id) === $profession->categorie_id) {{ 'Selected' }} @endif>
                                        {{ $category->libcat }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-danger" type="submit">
                            Validez
                        </button>
                    </div>
            </form>
        </div>
    </div>
@endsection
@section('js')
    <script src="{{ asset('adminlte/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
    <script>
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    </script>
@endsection