routes/web.php
<?php


use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('decisions/afficher_taux', 'DecisionController@taux')->name('decisions.afficher_taux');

Route::post('decision/tauxremboursement', 'DecisionController@tauxremboursement')->name('decision.tauxremboursement');

Route::resource('categories', 'CategorieController');

Route::resource('professions', 'ProfessionController');

Route::resource('produitcredits', 'ProduitcreditController');

Route::resource('typedemandeurs', 'TypedemandeurController');

Route::resource('sexes', 'SexeController');

Route::resource('sitmatrimoniales', 'SitmatrimonialeController');

Route::resource('niveaux', 'NiveauController');

Route::resource('decisions', 'DecisionController');

app/Models/Produitcredit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Produitcredit extends Model
{
    //
    protected $table = 'produitcredits';

    protected $fillable = [
        'codepc',
        'libpc',
        'created_at',
        'updated_at'
    ];
}

app/Http/Controllers/ProduitcreditController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produitcredit;
use Illuminate\Http\Request;

use App\Http\Requests\produitcreditRequestCreate;

class ProduitcreditController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $produitcredits = Produitcredit::all();
        return view('produitcredits/index', compact('produitcredits'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('produitcredits/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(produitcreditRequestCreate $request)
    {
        //
        Produitcredit::create($request->all());
        return back()->with('success', 'Produit bien ajouté');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Produitcredit  $produitcredit
     * @return \Illuminate\Http\Response
     */
    public function show(Produitcredit $produitcredit)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Produitcredit  $produitcredit
     * @return \Illuminate\Http\Response
     */
    public function edit(Produitcredit $produitcredit)
    {
        //
        return view('produitcredits.update', compact('produitcredit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Produitcredit  $produitcredit
     * @return \Illuminate\Http\Response
     */
    public function update(produitcreditRequestCreate $request, Produitcredit $produitcredit)
    {
        //
        $produitcredits = Produitcredit::all();
        $produitcredit->update($request->all());
        \Session::flash('success', 'Mise à jour de la catégorie effectuée avec succès');
        return redirect()->action('ProduitcreditController@index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Produitcredit  $produitcredit
     * @return \Illuminate\Http\Response
     */
    public function destroy(Produitcredit $produitcredit)
    {
        //
        $produitcredit->delete();
        $produitcredits = Produitcredit::all();
        \Session::flash('success', 'La catégorie a été supprimée avec succès');
        return redirect()->action('ProduitcreditController@index');
    }
}

resources/views/produitcredits/create.blade.php
@extends('layouts.main')

@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css') }}">
@endsection

@section('content')
    <div class="card">
        <div class="card-header">

        </div>


        <div class="card-body">
            <form method="POST" action="{{ route('produitcredits.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="codepc">Code du produit</label>
                            <input class="form-control {{ $errors->has('codepc') ? 'is-invalid' : '' }}" type="text"
                                name="codepc" id="codepc" value="{{ old('codepc', '') }}" required>

                            @if ($errors->has('codepc'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('codepc') }}
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="required" for="libpc">Libellé du produit</label>
                            <input class="form-control {{ $errors->has('libpc') ? 'is-invalid' : '' }}" type="text"
                                name="libpc" id="libpc" value="{{ old('libpc', '') }}" required>

                            @if ($errors->has('libpc'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('libpc') }}
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-danger" type="submit">
                        Validez
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('js')
    <script src="{{ asset('adminlte/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
    <script>
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    </script>
@endsection

resources/views/produitcredits/index.blade.php
@extends('layouts.main')
@section('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css">
@endsection
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="col-sm-2 pull-right" style="margin-bottom: 10px">

                    <a href="{{ route('home') }}">
                        <button type="button" class="btn btn-block btn-outline-primary btn-sm">Retour</button>
                    </a>

                </div>

                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Liste des produits crédits</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped datatable-Transaction">
                            <thead>
                                <tr>
                                    <th>id</th>
                                    <th>Code du produit</th>
                                    <th>Libellé du produit</th>

                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($produitcredits as $key => $produitcredit)
                                    <tr>
                                        <td>{{ $produitcredit->id ?? '' }}</td>

                                        <td>{{ $produitcredit->codepc ?? '' }}</td>
                                        <td>{{ $produitcredit->libpc ?? '' }}</td>


                                        <td class="">
                                            <div class="btn-group btn-group-sm">

                                                {!! Form::open(['route' => ['produitcredits.destroy', $produitcredit->id], 'method' => 'delete']) !!}
                                                <div class='btn-group'>

                                                    <a href="{{ route('produitcredits.edit', $produitcredit->id) }}"
                                                        class='btn btn-warning'>
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                    {!! Form::button('<i class="fa fa-trash"></i>', [
                                                        'type' => 'submit',
                                                        'class' => 'btn btn-sm  btn-square btn-danger',
                                                        'onclick' => "return confirm('Êtes vous sûr de supprimer ?')",
                                                    ]) !!}

                                                </div>
                                                {!! Form::close() !!}

                                            </div>
                                        </td>


                                    </tr>
                                @endforeach



                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>id</th>
                                    <th>Code du produit</th>
                                    <th>Libellé du produit</th>

                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->


    </section>
@endsection
@section('js')
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>

    <script>
        $(function() {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
                dom: 'Bfrtip',
                buttons: [

                    'excelHtml5',
                    'csvHtml5',
                    'pdfHtml5'
                ]
            });





        });
    </script>
@endsection

resources/views/produitcredits/update.blade.php
@extends('layouts.main')

@section('css')
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css') }}">
@endsection

@section('content')
    <div class="card">
        <div class="card-header">

        </div>


        <div class="card-body">

            {!! Form::model($produitcredit, ['method' => 'PATCH', 'route' => ['produitcredits.update', $produitcredit->id]]) !!}

            @method('PUT')
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="required" for="codepc">Code du produit</label>
                        <input class="form-control {{ $errors->has('codepc') ? 'is-invalid' : '' }}" type="text"
                            name="codepc" id="codepc" value="{{ $produitcredit->codepc }}" required>

                        @if ($errors->has('codepc'))
                            <div class="invalid-feedback">
                                {{ $errors->first('codepc') }}
                            </div>
                        @endif
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="required" for="libpc">Libellé du produit</label>
                        <input class="form-control {{ $errors->has('libpc') ? 'is-invalid' : '' }}" type="text"
                            name="libpc" id="libpc" value="{{ $produitcredit->libpc }}" required>

                        @if ($errors->has('libpc'))
                            <div class="invalid-feedback">
                                {{ $errors->first('libpc') }}
                            </div>
                        @endif
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    Validez
                </button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection
@section('js')
    <script src="{{ asset('adminlte/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
    <script>
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    </script>
@endsection